import type { NetworkContactFormData } from '../types/Network';

// Seed data from Excel - Network contacts
export const networkSeedData: NetworkContactFormData[] = [
      {
            companyName: 'Tuzla Gisan',
            contactPerson: 'Burak Açıkgüllü',
            phone: '0 533 086 15 81',
            email: '',
            category: 'YENI_INSA',
            serviceArea: 'BORU',
            shipType: 'Tanker',
            contactStatus: 'ULASILDI',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: 'Boru için mail atacak, yeni inşa Gemi',
      },
      {
            companyName: 'Çeksan',
            contactPerson: 'Cihan bayrak',
            phone: '0 537 318 02 57',
            email: '',
            category: 'TAMIR',
            serviceArea: 'BORU_TECHIZ',
            shipType: 'Tamir gemisi',
            contactStatus: 'ULASILDI',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: '',
      },
      {
            companyName: 'Hicri Ercil',
            contactPerson: 'Bülent Ogeyik',
            phone: '',
            email: '',
            category: 'YENI_INSA',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILMIYOR',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: '',
      },
      {
            companyName: 'Gemak',
            contactPerson: 'Soner Yılmaz',
            phone: '',
            email: '',
            category: 'YENI_INSA',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: '',
      },
      {
            companyName: 'Yalova Shipyard',
            contactPerson: 'Serkan karamanlı',
            phone: '',
            email: '',
            category: 'TAMIR',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: '',
      },
      {
            companyName: 'Sefine Tersanesi-Tamir',
            contactPerson: 'Ömer kurt',
            phone: '',
            email: '',
            category: 'TAMIR',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: '',
      },
      {
            companyName: 'Tersan Tersanesi-Tamir',
            contactPerson: 'Deniz',
            phone: '',
            email: '',
            category: 'TAMIR',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'HAYIR',
            result: 'RED',
            notes: '',
      },
      {
            companyName: 'Sedef Shipard',
            contactPerson: 'Serdar Özbay',
            phone: '',
            email: '',
            category: 'YENI_INSA',
            serviceArea: 'BORU_TECHIZ',
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: '',
      },
      {
            companyName: 'Desan',
            contactPerson: '',
            phone: '',
            email: '',
            category: 'DIGER',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'BEKLEMEDE',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: '',
      },
      {
            companyName: 'RMK',
            contactPerson: 'Mithat Rüstem ekici',
            phone: '',
            email: '',
            category: 'YENI_INSA',
            serviceArea: 'BORU',
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'TEKLIF_BEKLENIYOR',
            result: undefined,
            notes: 'Teklif için mail bekleniyor',
      },
      {
            companyName: 'Kuzey Star',
            contactPerson: 'Ali Özcan bayrak',
            phone: '',
            email: '',
            category: 'DIGER',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'HAYIR',
            result: 'IS_YOK',
            notes: 'İş yok',
      },
      {
            companyName: 'Mengi Yay',
            contactPerson: 'Hüseyin Mengi',
            phone: '',
            email: '',
            category: 'YAT',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'TEKLIF_BEKLENIYOR',
            result: undefined,
            notes: 'Teklif için bekleniyor',
      },
      {
            companyName: 'Art',
            contactPerson: 'Erbil Yeşilyurt',
            phone: '',
            email: '',
            category: 'DIGER',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'HAYIR',
            result: 'RED',
            notes: '',
      },
      {
            companyName: 'Yalova gisan',
            contactPerson: 'Mustaf durdu',
            phone: '5462281881',
            email: '',
            category: 'TANKER',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'TEKLIF_BEKLENIYOR',
            result: undefined,
            notes: 'Teklif bekleniyor',
      },
      {
            companyName: 'Beşiktaş',
            contactPerson: 'İbrahim aydin',
            phone: '',
            email: '',
            category: 'TAMIR',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: 'ihtiyat halinde ilestisime gecilecek',
      },
      {
            companyName: 'Yatfactory',
            contactPerson: 'Hüseyin doğar',
            phone: '',
            email: '',
            category: 'YAT',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'TEKLIF_VERILECEK',
            result: undefined,
            notes: 'Teklif verilecek',
      },
      {
            companyName: 'Atlas',
            contactPerson: 'Burak bayındır',
            phone: '',
            email: '',
            category: 'YENI_INSA',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'ULASILDI',
            quoteStatus: 'GORUSME_DEVAM_EDIYOR',
            result: undefined,
            notes: 'Görüşme devam ediyor',
      },
      {
            companyName: 'Atlas',
            contactPerson: 'Kaan',
            phone: '',
            email: '',
            category: 'ASKERI_PROJE',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'BEKLEMEDE',
            quoteStatus: 'TEKLIF_VERILDI',
            result: 'DONUS_YOK',
            notes: 'teklif verildi dönüş yok',
      },
      {
            companyName: 'Uzmar',
            contactPerson: 'Burak Şengün',
            phone: '',
            email: '',
            category: 'DIGER',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'BEKLEMEDE',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: 'ihtiyaç halinde dönüş yapılcak',
      },
      {
            companyName: '',
            contactPerson: 'Varol Çakır',
            phone: '',
            email: '',
            category: 'DIGER',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'BEKLEMEDE',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: '',
      },
      {
            companyName: '',
            contactPerson: 'Tolga Cihangiroğlu',
            phone: '',
            email: '',
            category: 'DIGER',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'BEKLEMEDE',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: '',
      },
      {
            companyName: '',
            contactPerson: 'Abuzer',
            phone: '',
            email: '',
            category: 'DIGER',
            serviceArea: undefined,
            shipType: '',
            contactStatus: 'BEKLEMEDE',
            quoteStatus: 'HAYIR',
            result: undefined,
            notes: '',
      },
];
